### ISSUE TITLE
[CE 2.1 rc3]  error message on page load

### ISSUE THREAD

**Issue by Dayssam** [ClaudiuCreanga/magento2-stockists-extension#1]
Hi

This the error

![stockists](https://cloud.githubusercontent.com/assets/13301885/16582363/fe53dc90-429d-11e6-9897-019656e7d194.png)

**Comment by ClaudiuCreanga** [comment]
Hi, 

It says in the readme: 

> This is a stockists extension for magento2, currently alpha 

I just started working on it so it is alpha.

**Comment by Dayssam** [comment]
@ClaudiuCreanga 
i know , i'm creating this issue to make you keep track of bugs.

Best regards

**Comment by ClaudiuCreanga** [comment]
Extension now working.
